<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Kriteria;
use Illuminate\Support\Facades\DB;

class KriteriaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $data = [
            // Contoh entri awal, silakan lanjutkan hingga total 494 entri
            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C1', 'nilai' => '2'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C1', 'nilai' => '4'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C1', 'nilai' => '3'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C1', 'nilai' => '4'],


            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C2', 'nilai' => '3'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C2', 'nilai' => '3'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C2', 'nilai' => '5'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C2', 'nilai' => '4'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C2', 'nilai' => '3'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C2', 'nilai' => '3'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C2', 'nilai' => '5'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C2', 'nilai' => '2'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C2', 'nilai' => '4'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C2', 'nilai' => '5'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C2', 'nilai' => '4'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C2', 'nilai' => '2'],



            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C3', 'nilai' => '2'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C3', 'nilai' => '1'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C3', 'nilai' => '4'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C3', 'nilai' => '2'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C3', 'nilai' => '4'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C3', 'nilai' => '2'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C3', 'nilai' => '1'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C3', 'nilai' => '4'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C3', 'nilai' => '2'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C3', 'nilai' => '4'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C3', 'nilai' => '5'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C3', 'nilai' => '2'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C3', 'nilai' => '3'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C3', 'nilai' => '5'],


            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C4', 'nilai' => '1'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C4', 'nilai' => '3'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C4', 'nilai' => '1'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C4', 'nilai' => '5'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C4', 'nilai' => '3'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C4', 'nilai' => '5'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C4', 'nilai' => '2'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C4', 'nilai' => '4'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C4', 'nilai' => '5'],



            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C5', 'nilai' => '2'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C5', 'nilai' => '2'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C5', 'nilai' => '4'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C5', 'nilai' => '2'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C5', 'nilai' => '5'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C5', 'nilai' => '2'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C5', 'nilai' => '2'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C5', 'nilai' => '5'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C5', 'nilai' => '1'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C5', 'nilai' => '4'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C5', 'nilai' => '3'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C5', 'nilai' => '4'],





            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C6', 'nilai' => '4'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C6', 'nilai' => '2'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C6', 'nilai' => '4'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C6', 'nilai' => '2'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C6', 'nilai' => '3'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C6', 'nilai' => '3'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C6', 'nilai' => '1'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C6', 'nilai' => '5'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C6', 'nilai' => '4'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C6', 'nilai' => '2'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C6', 'nilai' => '4'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C6', 'nilai' => '1'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C6', 'nilai' => '3'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C6', 'nilai' => '3'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C6', 'nilai' => '2'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C6', 'nilai' => '2'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C6', 'nilai' => '4'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C6', 'nilai' => '1'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C6', 'nilai' => '2'],

            ['kode_distrik' => 'A1', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A2', 'kode_kriteria' => 'C7', 'nilai' => '3'],
            ['kode_distrik' => 'A3', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A4', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A5', 'kode_kriteria' => 'C7', 'nilai' => '5'],
            ['kode_distrik' => 'A6', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A7', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A8', 'kode_kriteria' => 'C7', 'nilai' => '3'],
            ['kode_distrik' => 'A9', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A10', 'kode_kriteria' => 'C7', 'nilai' => '3'],
            ['kode_distrik' => 'A11', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A12', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A13', 'kode_kriteria' => 'C7', 'nilai' => '5'],
            ['kode_distrik' => 'A14', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A15', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A16', 'kode_kriteria' => 'C7', 'nilai' => '3'],
            ['kode_distrik' => 'A17', 'kode_kriteria' => 'C7', 'nilai' => '4'],
            ['kode_distrik' => 'A18', 'kode_kriteria' => 'C7', 'nilai' => '2'],
            ['kode_distrik' => 'A19', 'kode_kriteria' => 'C7', 'nilai' => '3'],

//    // C8
//     ['kode_distrik' => 'A1', 'kode_kriteria' => 'C8', 'nilai' => 3],
//     ['kode_distrik' => 'A2', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A3', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A4', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A5', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A6', 'kode_kriteria' => 'C8', 'nilai' => 3],
//     ['kode_distrik' => 'A7', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A8', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A9', 'kode_kriteria' => 'C8', 'nilai' => 3],
//     ['kode_distrik' => 'A10', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A11', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A12', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A13', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A14', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A15', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A16', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A17', 'kode_kriteria' => 'C8', 'nilai' => 4],
//     ['kode_distrik' => 'A18', 'kode_kriteria' => 'C8', 'nilai' => 2],
//     ['kode_distrik' => 'A19', 'kode_kriteria' => 'C8', 'nilai' => 1],

//     // C9
//     ['kode_distrik' => 'A1', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A2', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A3', 'kode_kriteria' => 'C9', 'nilai' => 4],
//     ['kode_distrik' => 'A4', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A5', 'kode_kriteria' => 'C9', 'nilai' => 4],
//     ['kode_distrik' => 'A6', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A7', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A8', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A9', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A10', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A11', 'kode_kriteria' => 'C9', 'nilai' => 4],
//     ['kode_distrik' => 'A12', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A13', 'kode_kriteria' => 'C9', 'nilai' => 4],
//     ['kode_distrik' => 'A14', 'kode_kriteria' => 'C9', 'nilai' => 3],
//     ['kode_distrik' => 'A15', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A16', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A17', 'kode_kriteria' => 'C9', 'nilai' => 4],
//     ['kode_distrik' => 'A18', 'kode_kriteria' => 'C9', 'nilai' => 2],
//     ['kode_distrik' => 'A19', 'kode_kriteria' => 'C9', 'nilai' => 1],

//     // C10
//     ['kode_distrik' => 'A1', 'kode_kriteria' => 'C10', 'nilai' => 4],
//     ['kode_distrik' => 'A2', 'kode_kriteria' => 'C10', 'nilai' => 3],
//     ['kode_distrik' => 'A3', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A4', 'kode_kriteria' => 'C10', 'nilai' => 4],
//     ['kode_distrik' => 'A5', 'kode_kriteria' => 'C10', 'nilai' => 5],
//     ['kode_distrik' => 'A6', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A7', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A8', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A9', 'kode_kriteria' => 'C10', 'nilai' => 4],
//     ['kode_distrik' => 'A10', 'kode_kriteria' => 'C10', 'nilai' => 3],
//     ['kode_distrik' => 'A11', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A12', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A13', 'kode_kriteria' => 'C10', 'nilai' => 5],
//     ['kode_distrik' => 'A14', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A15', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A16', 'kode_kriteria' => 'C10', 'nilai' => 4],
//     ['kode_distrik' => 'A17', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A18', 'kode_kriteria' => 'C10', 'nilai' => 2],
//     ['kode_distrik' => 'A19', 'kode_kriteria' => 'C10', 'nilai' => 2],

//     // C11
//     ['kode_distrik' => 'A1', 'kode_kriteria' => 'C11', 'nilai' => 2],
//     ['kode_distrik' => 'A2', 'kode_kriteria' => 'C11', 'nilai' => 1],
//     ['kode_distrik' => 'A3', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A4', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A5', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A6', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A7', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A8', 'kode_kriteria' => 'C11', 'nilai' => 2],
//     ['kode_distrik' => 'A9', 'kode_kriteria' => 'C11', 'nilai' => 2],
//     ['kode_distrik' => 'A10', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A11', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A12', 'kode_kriteria' => 'C11', 'nilai' => 3],
//     ['kode_distrik' => 'A13', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A14', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A15', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A16', 'kode_kriteria' => 'C11', 'nilai' => 1],
//     ['kode_distrik' => 'A17', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A18', 'kode_kriteria' => 'C11', 'nilai' => 4],
//     ['kode_distrik' => 'A19', 'kode_kriteria' => 'C11', 'nilai' => 1],

//     // C12
//     ['kode_distrik' => 'A1', 'kode_kriteria' => 'C12', 'nilai' => 2],
//     ['kode_distrik' => 'A2', 'kode_kriteria' => 'C12', 'nilai' => 1],
//     ['kode_distrik' => 'A3', 'kode_kriteria' => 'C12', 'nilai' => 3],
//     ['kode_distrik' => 'A4', 'kode_kriteria' => 'C12', 'nilai' => 2],
//     ['kode_distrik' => 'A5', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A6', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A7', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A8', 'kode_kriteria' => 'C12', 'nilai' => 1],
//     ['kode_distrik' => 'A9', 'kode_kriteria' => 'C12', 'nilai' => 2],
//     ['kode_distrik' => 'A10', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A11', 'kode_kriteria' => 'C12', 'nilai' => 3],
//     ['kode_distrik' => 'A12', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A13', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A14', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A15', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A16', 'kode_kriteria' => 'C12', 'nilai' => 1],
//     ['kode_distrik' => 'A17', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A18', 'kode_kriteria' => 'C12', 'nilai' => 4],
//     ['kode_distrik' => 'A19', 'kode_kriteria' => 'C12', 'nilai' => 1],




       // C8
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C8', 'nilai' => 3],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C8', 'nilai' => 3],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C8', 'nilai' => 3],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C8', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C8', 'nilai' => 2],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C8', 'nilai' => 1],



    // C9
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C9', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C9', 'nilai' => 4],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C9', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C9', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C9', 'nilai' => 3],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C9', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C9', 'nilai' => 2],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C9', 'nilai' => 1],

    // C10
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C10', 'nilai' => 4],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C10', 'nilai' => 3],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C10', 'nilai' => 4],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C10', 'nilai' => 5],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C10', 'nilai' => 4],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C10', 'nilai' => 3],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C10', 'nilai' => 5],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C10', 'nilai' => 4],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C10', 'nilai' => 2],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C10', 'nilai' => 2],

    // C11
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C11', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C11', 'nilai' => 1],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C11', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C11', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C11', 'nilai' => 3],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C11', 'nilai' => 1],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C11', 'nilai' => 4],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C11', 'nilai' => 1],

 // C12
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C12', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C12', 'nilai' => 1],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C12', 'nilai' => 3],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C12', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C12', 'nilai' => 1],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C12', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C12', 'nilai' => 3],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C12', 'nilai' => 1],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C12', 'nilai' => 4],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C12', 'nilai' => 1],

    // C13
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C13', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C13', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C13', 'nilai' => 1],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C13', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C13', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C13', 'nilai' => 3],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C13', 'nilai' => 4],

    // C14
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C14', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C14', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C14', 'nilai' => 3],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C14', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C14', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C14', 'nilai' => 5],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C14', 'nilai' => 1],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C14', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C14', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C14', 'nilai' => 3],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C14', 'nilai' => 5],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C14', 'nilai' => 5],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C14', 'nilai' => 4],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C14', 'nilai' => 4],

    // C15
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C15', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C15', 'nilai' => 1],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C15', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C15', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C15', 'nilai' => 4],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C15', 'nilai' => 5],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C15', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C15', 'nilai' => 1],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C15', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C15', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C15', 'nilai' => 5],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C15', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C15', 'nilai' => 3],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C15', 'nilai' => 5],

    // C16
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C16', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C16', 'nilai' => 1],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C16', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C16', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C16', 'nilai' => 5],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C16', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C16', 'nilai' => 1],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C16', 'nilai' => 2],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C16', 'nilai' => 3],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C16', 'nilai' => 5],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C16', 'nilai' => 4],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C16', 'nilai' => 5],

    // C17
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C17', 'nilai' => 2],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C17', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C17', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C17', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C17', 'nilai' => 4],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C17', 'nilai' => 2],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C17', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C17', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C17', 'nilai' => 1],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C17', 'nilai' => 4],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C17', 'nilai' => 3],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C17', 'nilai' => 4],

    // C18
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C18', 'nilai' => 4],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C18', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C18', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C18', 'nilai' => 2],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C18', 'nilai' => 3],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C18', 'nilai' => 3],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C18', 'nilai' => 1],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C18', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C18', 'nilai' => 4],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C18', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C18', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C18', 'nilai' => 1],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C18', 'nilai' => 3],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C18', 'nilai' => 3],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C18', 'nilai' => 1],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C18', 'nilai' => 2],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C18', 'nilai' => 3],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C18', 'nilai' => 1],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C18', 'nilai' => 2],

    // C19
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C19', 'nilai' => 3],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C19', 'nilai' => 5],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C19', 'nilai' => 3],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C19', 'nilai' => 3],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C19', 'nilai' => 4],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C19', 'nilai' => 5],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C19', 'nilai' => 3],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C19', 'nilai' => 2],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C19', 'nilai' => 3],

    // C20
    ['kode_distrik' => 'A1', 'kode_kriteria' => 'C20', 'nilai' => 3],
    ['kode_distrik' => 'A2', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A3', 'kode_kriteria' => 'C20', 'nilai' => 4],
    ['kode_distrik' => 'A4', 'kode_kriteria' => 'C20', 'nilai' => 4],
    ['kode_distrik' => 'A5', 'kode_kriteria' => 'C20', 'nilai' => 4],
    ['kode_distrik' => 'A6', 'kode_kriteria' => 'C20', 'nilai' => 3],
    ['kode_distrik' => 'A7', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A8', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A9', 'kode_kriteria' => 'C20', 'nilai' => 5],
    ['kode_distrik' => 'A10', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A11', 'kode_kriteria' => 'C20', 'nilai' => 4],
    ['kode_distrik' => 'A12', 'kode_kriteria' => 'C20', 'nilai' => 1],
    ['kode_distrik' => 'A13', 'kode_kriteria' => 'C20', 'nilai' => 4],
    ['kode_distrik' => 'A14', 'kode_kriteria' => 'C20', 'nilai' => 3],
    ['kode_distrik' => 'A15', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A16', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A17', 'kode_kriteria' => 'C20', 'nilai' => 3],
    ['kode_distrik' => 'A18', 'kode_kriteria' => 'C20', 'nilai' => 2],
    ['kode_distrik' => 'A19', 'kode_kriteria' => 'C20', 'nilai' => 2],

   ['kode_distrik' => 'A1', 'kode_kriteria' => 'C21', 'nilai' => 4],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C21', 'nilai' => 3],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C21', 'nilai' => 4],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C21', 'nilai' => 5],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C21', 'nilai' => 4],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C21', 'nilai' => 3],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C21', 'nilai' => 3],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C21', 'nilai' => 1],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C21', 'nilai' => 5],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C21', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C21', 'nilai' => 1],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C21', 'nilai' => 4],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C21', 'nilai' => 2],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C21', 'nilai' => 4],



// C22
['kode_distrik' => 'A1', 'kode_kriteria' => 'C22', 'nilai' => 2],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C22', 'nilai' => 1],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C22', 'nilai' => 1],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C22', 'nilai' => 1],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C22', 'nilai' => 2],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C22', 'nilai' => 3],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C22', 'nilai' => 1],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C22', 'nilai' => 4],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C22', 'nilai' => 1],

// C23
['kode_distrik' => 'A1', 'kode_kriteria' => 'C23', 'nilai' => 2],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C23', 'nilai' => 1],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C23', 'nilai' => 3],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C23', 'nilai' => 2],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C23', 'nilai' => 1],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C23', 'nilai' => 1],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C23', 'nilai' => 3],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C23', 'nilai' => 2],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C23', 'nilai' => 1],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C23', 'nilai' => 4],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C23', 'nilai' => 1],

// C24
['kode_distrik' => 'A1', 'kode_kriteria' => 'C24', 'nilai' => 2],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C24', 'nilai' => 1],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C24', 'nilai' => 3],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C24', 'nilai' => 3],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C24', 'nilai' => 3],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C24', 'nilai' => 1],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C24', 'nilai' => 5],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C24', 'nilai' => 1],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C24', 'nilai' => 3],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C24', 'nilai' => 3],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C24', 'nilai' => 1],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C24', 'nilai' => 4],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C24', 'nilai' => 1],

// C25
['kode_distrik' => 'A1', 'kode_kriteria' => 'C25', 'nilai' => 2],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C25', 'nilai' => 1],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C25', 'nilai' => 3],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C25', 'nilai' => 2],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C25', 'nilai' => 1],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C25', 'nilai' => 2],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C25', 'nilai' => 1],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C25', 'nilai' => 3],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C25', 'nilai' => 5],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C25', 'nilai' => 1],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C25', 'nilai' => 4],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C25', 'nilai' => 1],

// C26
['kode_distrik' => 'A1', 'kode_kriteria' => 'C26', 'nilai' => 2],
['kode_distrik' => 'A2', 'kode_kriteria' => 'C26', 'nilai' => 1],
['kode_distrik' => 'A3', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A4', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A5', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A6', 'kode_kriteria' => 'C26', 'nilai' => 4],
['kode_distrik' => 'A7', 'kode_kriteria' => 'C26', 'nilai' => 4],
['kode_distrik' => 'A8', 'kode_kriteria' => 'C26', 'nilai' => 1],
['kode_distrik' => 'A9', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A10', 'kode_kriteria' => 'C26', 'nilai' => 1],
['kode_distrik' => 'A11', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A12', 'kode_kriteria' => 'C26', 'nilai' => 5],
['kode_distrik' => 'A13', 'kode_kriteria' => 'C26', 'nilai' => 3],
['kode_distrik' => 'A14', 'kode_kriteria' => 'C26', 'nilai' => 4],
['kode_distrik' => 'A15', 'kode_kriteria' => 'C26', 'nilai' => 4],
['kode_distrik' => 'A16', 'kode_kriteria' => 'C26', 'nilai' => 1],
['kode_distrik' => 'A17', 'kode_kriteria' => 'C26', 'nilai' => 4],
['kode_distrik' => 'A18', 'kode_kriteria' => 'C26', 'nilai' => 5],
['kode_distrik' => 'A19', 'kode_kriteria' => 'C26', 'nilai' => 1]



    ];
  DB::table('topses')->insert($data);

// C12  =	2	1	3	2	4	4	4	1	2	4	3	4	4	4	4	1	4	4	1

// C13 = 	2	2	3	3	4	4	3	1	2	3	3	3	4	4	3	4	4	3	4
// C14 = 	2	2	3	2	3	5	4	1	2	2	3	4	4	5	4	4	5	4	4
// C15 = 	2	1	4	2	3	4	3	5	2	1	4	3	3	4	3	5	4	3	5
// C16 = 	2	1	4	2	3	4	4	5	2	1	4	2	3	4	4	5	4	4	5
// C17 = 	2	2	4	2	3	3	3	4	2	2	4	1	3	3	3	4	3	3	4
// C18 = 	4	2	4	2	3	3	1	2	4	2	4	1	3	3	1	2	3	1	2
// C19 = 	4	3	4	4	5	2	2	3	4	3	4	4	5	2	2	3	2	2	3
// C20 = 	3	2	4	4	4	3	2	2	5	2	4	1	4	3	2	2	3	2	2
// C21 = 	4	3	2	4	5	2	2	4	3	3	2	1	5	4	1	4	2	2	4
// C22 = 	2	1	3	3	3	4	4	1	3	1	3	2	3	4	4	1	4	4	1
// C23 = 	2	1	3	2	4	4	4	1	4	1	3	2	4	4	4	1	4	4	1
// C24 = 	2	1	3	3	3	4	4	1	5	1	3	4	3	4	4	1	4	4	1
// C25 = 	2	1	3	2	4	4	4	1	2	1	3	4	4	4	5	1	4	4	1
// C26 = 	2	1	3	3	3	4	4	1	3	1	3	5	3	4	4	1	4	5	1



    }
}
